---
- name: Install Apache
  yum:
    name: httpd
    state: present
  notify: Pull /var/cache/yum

- name: Enable Apache
  service:
    name: httpd
    enabled: yes
    
- name: Install FastCGI module for Apache
  yum:
    name: mod_fcgid
    state: present
  notify: Pull /var/cache/yum

# Increase mod_fcgid request size to handle attachments in RT
# https://www.bestpractical.com/docs/rt/4.2.12/web_deployment.html
- name: Configure mod_fcgid
  lineinfile:
    dest: /etc/httpd/conf.d/fcgid.conf
    line: FcgidMaxRequestLen 1073741824
    state: present

- name: Install mod_ssl
  yum:
    name: mod_ssl
    state: present
  notify: Pull /var/cache/yum

- name: Insert sites-enabled include in httpd.conf
  lineinfile:
    line: IncludeOptional sites-enabled/*.conf
    state: present
    dest: /etc/httpd/conf/httpd.conf
    insertafter: IncludeOptional conf.d/*.conf

- name: Create sites-available
  file:
    path: /etc/httpd/sites-available
    state: directory
    owner: root
    group: root
    mode: 0755
    seuser: system_u
    serole: object_r
    setype: httpd_config_t

- name: Create sites-enabled
  file:
    path: /etc/httpd/sites-enabled
    state: directory
    owner: root
    group: root
    mode: 0755
    seuser: system_u
    serole: object_r
    setype: httpd_config_t

- name: Configure Apache RT site
  template:
    src: rt.conf
    dest: /etc/httpd/sites-available/rt.conf
    owner: root
    group: root
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: httpd_config_t

- name: Enable Apache RT site
  file:
    path: /etc/httpd/sites-enabled/rt.conf
    state: link
    src: /etc/httpd/sites-available/rt.conf
    owner: root
    group: root
    seuser: system_u
    serole: object_r
    setype: httpd_config_t
    
#- include: install_rt_ext.yml
#  vars:
#    ext: "{{ extensions.ResetPassword }}"
